services:
  scantrix-dev:
    build:
      context: .
      target: dev
    container_name: scantrix-dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true

  scantrix:
    build:
      context: .
      target: binary
    container_name: scantrix
