# .github/workflows/build.yml
name: Build & Release Scantrix

on:
  push:
    tags:
      - 'v*'  # Only build on version tags like v0.1.0

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64  # Skip unsupported combo

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          go build -o dist/scantrix-${{ matrix.goos }}-${{ matrix.goarch }}$EXT ./cmd/scantrix

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        if: startsWith(github.ref, 'refs/tags/')
